spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: topic4db
      uuid-representation: standard
#      auto-index-creation: 'true'
#      authentication-database: 'admin'
#      connections-per-host: '8'
#      socket-timeout: '300000'
#      max-wait-time: '120000'
#      ssl:
#        enabled: 'false'
#        invalid-hostname-allowed: 'false'

hibernate:
  ogm:
    datastore:
      provider: MONGODB
      create_database: 'true'
      database: hike_db

#Logging
logging:
  level:
    com:
      ecommerce: DEBUG
    org:
      springframework: INFO

min-page: 0
max-page: 25
