server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: '<rabbitmq username>'
    password: '<rabbitmq password>'

rabbitmq:
  exchange:
    name: demo_exchange
  queue:
    name: demo
  routing:
    key: demo_routing_key