# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    # schedule:
    # Runs "At 02:00" (see https://crontab.guru)
    # - cron: '0 2 * * *'
    push:
        branches:
            - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "greet"
    greet:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                collection: [{ "num": "1" }, { "num": "2" }, { "num": "3" }]

        outputs:
          output1: ${{ steps.step_1.outputs.url }}
          output2: ${{ steps.step_2.outputs.url }}
          output3: ${{ steps.step_3.outputs.url }}
        
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - run: mkdir -p path/to/artifact
            - run: echo hello > path/to/artifact/world_${{matrix.collection.num}}.txt
            - name: Output the run Details
              uses: actions/upload-artifact@v4
              id: artifact-upload-step
              with:
                  name: RunReports_${{matrix.collection.num}}
                  path: path/to/artifact/world_${{matrix.collection.num}}.txt

            - name: Set artifact URL
              id: step_${{ matrix.collection.num }}
              run: echo 'url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}'  >> "$GITHUB_OUTPUT"

    send-mail:
        runs-on: ubuntu-latest
        needs: [greet]
        steps:
          - name: Print artifact URL
            run: echo ${{ needs.greet.outputs.output1 }} ${{ needs.greet.outputs.output2 }} ${{ needs.greet.outputs.output3 }}

          # - uses: actions/download-artifact@v4
          #   id: download
          #   with:
          #     path: path/to/artifact
          # - name: Use Artifacts
          #   run: |
          #     echo "Downloaded artifact URLs:"
          #     echo "${{ steps.download.outputs.download-path }}"

          # - name: Send mail
          #   uses: dawidd6/action-send-mail@v3
          #   with:
          #       server_address: smtp.gmail.com
          #       # Server port, default 25:
          #       server_port: 465
          #       # Optional whether this connection use TLS (default is true if server_port is 465)
          #       secure: true
          #       # Optional (recommended) mail server username:
          #       username: nguyenhung12c1@gmail.com
          #       # Optional (recommended) mail server password:
          #       password: ufqo hkyb maub vhjq
          #       # Required mail subject:
          #       subject: TEST ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          #       # Required recipients' addresses:
          #       to: sieupha2712@gmail.com
          #       # Required sender full name (address can be skipped):
          #       from: nguyenhung12c1@gmail.com
          #       body: |
          #           ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          #           GitHub repository: ${{ github.repository }}
          #           Links to the HTML files:
          #               - [RunReport_1](${{ env.Artifact_1 }})
          #               - [RunReport_2](${{ env.Artifact_2 }})
          #               - [RunReport_3](${{ env.Artifact_3 }})
          #       # Optional priority: 'high', 'normal' (default) or 'low'
          #       priority: normal
